require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/projects_to_manies", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProjectsToMany. As you add validations to ProjectsToMany, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProjectsToMany.create! valid_attributes
      get projects_to_manies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      projects_to_many = ProjectsToMany.create! valid_attributes
      get projects_to_many_url(projects_to_many)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_projects_to_many_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      projects_to_many = ProjectsToMany.create! valid_attributes
      get edit_projects_to_many_url(projects_to_many)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProjectsToMany" do
        expect {
          post projects_to_manies_url, params: { projects_to_many: valid_attributes }
        }.to change(ProjectsToMany, :count).by(1)
      end

      it "redirects to the created projects_to_many" do
        post projects_to_manies_url, params: { projects_to_many: valid_attributes }
        expect(response).to redirect_to(projects_to_many_url(ProjectsToMany.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProjectsToMany" do
        expect {
          post projects_to_manies_url, params: { projects_to_many: invalid_attributes }
        }.to change(ProjectsToMany, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post projects_to_manies_url, params: { projects_to_many: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested projects_to_many" do
        projects_to_many = ProjectsToMany.create! valid_attributes
        patch projects_to_many_url(projects_to_many), params: { projects_to_many: new_attributes }
        projects_to_many.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the projects_to_many" do
        projects_to_many = ProjectsToMany.create! valid_attributes
        patch projects_to_many_url(projects_to_many), params: { projects_to_many: new_attributes }
        projects_to_many.reload
        expect(response).to redirect_to(projects_to_many_url(projects_to_many))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        projects_to_many = ProjectsToMany.create! valid_attributes
        patch projects_to_many_url(projects_to_many), params: { projects_to_many: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested projects_to_many" do
      projects_to_many = ProjectsToMany.create! valid_attributes
      expect {
        delete projects_to_many_url(projects_to_many)
      }.to change(ProjectsToMany, :count).by(-1)
    end

    it "redirects to the projects_to_manies list" do
      projects_to_many = ProjectsToMany.create! valid_attributes
      delete projects_to_many_url(projects_to_many)
      expect(response).to redirect_to(projects_to_manies_url)
    end
  end
end
